# Generated by Django 4.0.4 on 2022-06-12 16:44

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_description', models.TextField()),
                ('movie_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('movie_release_date', models.DateField(blank=True, default=datetime.date(2022, 6, 12), null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
