# Generated by Django 4.0.3 on 2022-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='otp_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Key Expiration DateTime'),
        ),
    ]
