# Generated by Django 4.0.3 on 2022-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_whitelistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='user_type',
            field=models.CharField(default='AppUser', max_length=25),
        ),
    ]
