# Generated by Django 4.0.3 on 2022-05-28 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_usersinfo_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, default='India', max_length=255, null=True)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Authentication.usersinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
