# Generated by Django 4.0.3 on 2022-05-28 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Merchent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen_name', models.CharField(max_length=255)),
                ('screen_type', models.CharField(blank=True, default='Class-3', max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('theter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theter', to='Merchent.theterinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
