# Generated by Django 4.0.4 on 2022-06-01 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Merchent', '0002_screens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_name', models.CharField(max_length=255)),
                ('seat_price', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen', to='Merchent.screens')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
